name: NewsReader CI

on:
  push:
    branches:
      - main  # Runs CI/CD when code is pushed to the `main` branch
  pull_request:
    branches:
      - main  # Runs on pull requests to `main`

jobs:
  build:
    runs-on: macos-latest  # Uses macOS environment

    env:
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}  # Securely inject API Key

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones repo into GitHub runner

      - name: List Available Xcode Versions
        run: ls /Applications | grep Xcode

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app/Contents/Developer  # Use latest available version

      - name: Install Dependencies
        run: |
          brew install xcbeautify || true  # Install xcbeautify (for readable logs)
          pod install --project-directory=NewsReader  # Install CocoaPods (if using Pods)

      - name: Build and Test
        run: |
          export NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}  # Set API key as env variable
          xcodebuild test -workspace NewsReader.xcworkspace -scheme NewsReader -destination 'platform=iOS Simulator,name=iPhone 15 Pro' -only-testing:NewsReaderUITests/NewsViewControllerUITests | xcbeautify
