name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode 16.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Install dependencies
        run: |
          # Adjust these commands based on your package manager
          brew install swiftlint
          # Add other dependencies as needed

      - name: Build and test
        run: |
          xcodebuild -project NewsReader.xcodeproj \
            -scheme NewsReader \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' \
            clean test
