name: NewsReader CI

on:
  push:
    branches:
      - main  # Runs CI/CD when code is pushed to the `main` branch
  pull_request:
    branches:
      - main  # Runs on pull requests to `main`

jobs:
  build:
    runs-on: macos-latest  # Runs on macOS

    env:
      WEATHER_API_KEY: ${{ secrets.NEWS_API_KEY }}  # Inject API Key securely

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones repo into the GitHub runner
      
      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer

      - name: Build and Test
        run: |
          export NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}
          xcodebuild test -project NewsReader.xcodeproj -scheme NewsReader -destination 'platform=iOS Simulator,OS=18.2,name=iPhone 16 Pro'
